services:
  - type: web
    name: biblioteca-app
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan db:seed --class=RoleSeeder --force
      php artisan db:seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-app.onrender.com
      - key: APP_LOCALE
        value: es
      - key: APP_FALLBACK_LOCALE
        value: en
      - key: APP_FAKER_LOCALE
        value: es_ES
      - key: LOG_CHANNEL
        value: stack
      - key: LOG_LEVEL
        value: debug
      - key: SESSION_DRIVER
        value: database
      - key: SESSION_LIFETIME
        value: 120
      - key: SESSION_ENCRYPT
        value: false
      - key: QUEUE_CONNECTION
        value: database
      - key: CACHE_STORE
        value: database
      - key: FILESYSTEM_DISK
        value: local

      # Mail
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: badpruebas52@gmail.com
      - key: MAIL_PASSWORD
        value: wrmympzcspqwdimf
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: badpruebas52@gmail.com
      - key: MAIL_FROM_NAME
        value: Librarium

      # Base de datos (Render las enlaza automáticamente)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mysql-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mysql-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mysql-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mysql-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysql-db
          property: password

databases:
  - name: mysql-db
    plan: free
