services:
  - type: web
    name: laravel-app
    env: docker 
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan migrate --force
      php artisan db:seed --class=RoleSeeder --force
      php artisan db:seed --force
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: APP_URL
        value: https://laravel-app.onrender.com
      # Mail
      - key: MAIL_MAILER
        value: smtp
      - key: MAIL_HOST
        value: smtp.gmail.com
      - key: MAIL_PORT
        value: 587
      - key: MAIL_USERNAME
        value: badpruebas52@gmail.com
      - key: MAIL_PASSWORD
        value: wrmympzcspqwdimf
      - key: MAIL_ENCRYPTION
        value: tls
      - key: MAIL_FROM_ADDRESS
        value: badpruebas52@gmail.com
      - key: MAIL_FROM_NAME
        value: Librarium
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        fromDatabase:
          name: mysql-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: mysql-db
          property: port
      - key: DB_DATABASE
        fromDatabase:
          name: mysql-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: mysql-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: mysql-db
          property: password

databases:
  - name: mysql-db
    plan: free
